import { EventType, SubstitutionReason } from '@prisma/client'; // Import enums generated by Prisma

export interface MatchEventData {
  matchId: number;
  userId: number;
  minute: number;
  eventType: EventType; // Use the enum directly from Prisma
  substitutionReason?: SubstitutionReason | null; // Use the enum directly from Prisma
  playerInId?: number | null; // For substitution events
  playerOutId?: number | null; // For substitution events
}

export interface MatchPlayerData {
  userId: number;
  matchId: number;
  minutes: number;
  available: boolean;
}

export interface MatchFormData {
  matchType: 'PRACTICE' | 'COMPETITION';
  date: string | Date;
  pouleOpponentId?: number; // Optional for PRACTICE matches
  practiceOpponent?: string | null; // Optional and nullable for COMPETITION matches
}
